"""5 added posts class

Revision ID: 309c510eabf9
Revises: fd83b65d346b
Create Date: 2023-06-30 12:44:01.009010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309c510eabf9'
down_revision = 'fd83b65d346b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
